d_jview_homepage:
    path:     /
    defaults: { _controller: DJviewBundle:Default:index }
    
    
d_jview_detailfigure:
    path:    /figure/{id}
    defaults: {_controller: DJviewBundle:Default:detailfigure}
    

d_jview_inscription:
    path:    /inscription
    defaults: {_controller: DJviewBundle:Default:inscription}
    
   
    
    
d_jview_addfigure:
    path:    /ajoutFigure
    defaults: {_controller: DJviewBundle:Default:addfigures}

d_jview_delfigure:
    path:    /supprimerFigure/{id}
    defaults: {_controller: DJviewBundle:Figure:delfigure}