d_jview_homepage:
    path:     /
    defaults: { _controller: DJviewBundle:Default:index}
                             
    
d_jview_detailfigure:
    path:    /figure/{name}/{id}/{page}
    defaults: {_controller: DJviewBundle:Default:detailfigure, page: 0}
    

d_jview_inscription:
    path:    /inscription
    defaults: {_controller: DJviewBundle:Default:inscription}
         
    
d_jview_addfigure:
    path:    /ajoutFigure/
    defaults: {_controller: DJviewBundle:Default:addfigures}

d_jview_delfigure:
    path:    /supprimerFigure/{id}
    defaults: {_controller: DJviewBundle:Figure:delfigure}
    
d_jview_modification:
    path:    /modificationFigure/{id}
    defaults: {_controller: DJviewBundle:Figure:modificationfigure}
    
d_jview_modification_ajaxupload:
    path:    /ajaxpicture/{id}/{idarticle}
    defaults: {_controller: DJviewBundle:Figure:ajaxupload}
    
d_jview_modification_ajaxvideo:
    path:    /test/{id}
    defaults: {_controller: DJviewBundle:Figure:ajaxvideo}
    
d_jview_modification_ajaxdesciption:
    path:    /updatedescription/{id}
    defaults: {_controller: DJviewBundle:Figure:ajaxupdatedescription}
    
d_jview_fakedata:
    path:    /fakedata
    defaults: {_controller: DJviewBundle:Default:fixturesdoctrine}
    
d_jview_supprimerphoto:
    path:    /delPicture/{id}
    defaults: {_controller: DJviewBundle:Figure:ajaxsupp} 
    
    