d_jview_homepage:
    path:     /
    defaults: { _controller: DJviewBundle:Default:index}
                             
    
d_jview_detailfigure:
    path:    /figure/{name}/{id}/{page}
    defaults: {_controller: DJviewBundle:Default:detailfigure, page: 0}
    requirements:
        name: \D*
        id: \d*
        page: \d*
    

d_jview_inscription:
    path:    /inscription
    defaults: {_controller: DJviewBundle:Default:inscription}
         
    
d_jview_addfigure:
    path:    /ajoutFigure/
    defaults: {_controller: DJviewBundle:Default:addfigures}

d_jview_delfigure:
    path:    /supprimerFigure/{id}
    defaults: {_controller: DJviewBundle:Figure:delfigure}
    requirements:
        id: \d*
    
d_jview_modification:
    path:    /modificationFigure/{id}
    defaults: {_controller: DJviewBundle:Figure:modificationfigure}
    requirements:
        id: \d*
    
d_jview_modification_ajaxupload:
    path:    /ajaxpicture/{id}/{idarticle}
    defaults: {_controller: DJviewBundle:Figure:ajaxupload}
    requirements:
        id: \d*
        idarticle: \d*
    
d_jview_modification_ajaxvideo:
    path:    /test/{id}
    defaults: {_controller: DJviewBundle:Figure:ajaxvideo}
    requirements:
        id: \d*
    
d_jview_modification_ajaxdesciption:
    path:    /updatedescription/{id}
    defaults: {_controller: DJviewBundle:Figure:ajaxupdatedescription}
    requirements:
        id: \d*
    
d_jview_fakedata:
    path:    /fakedata
    defaults: {_controller: DJviewBundle:Default:fixturesdoctrine}
    
d_jview_supprimermedia:
    path:    /delPicture/{media}/{id}
    defaults: {_controller: DJviewBundle:Figure:ajaxsupp}
    
d_jview_testmail:
    path:    /mailtest
    defaults: {_controller: DJviewBundle:Default:test_mail}
    
d_jview_resetpass:
    path:    /resetpassword
    defaults: {_controller: DJviewBundle:Default:viewreset}
    
d_jview_sendresetpass:
    path:    /sendpassword
    defaults: {_controller: DJviewBundle:Default:resendPassword}
    
d_jview_blog_list:
    path:    /BlogListe
    defaults: {_controller: DJviewBundle:Figure:test}
    