d_jview_homepage:
    path:     /
    defaults: { _controller: DJviewBundle:Default:index, sucess: 0}
                             
    
d_jview_detailfigure:
    path:    /figure/{id}/{page}
    defaults: {_controller: DJviewBundle:Default:detailfigure, page: 1}
    

d_jview_inscription:
    path:    /inscription
    defaults: {_controller: DJviewBundle:Default:inscription}
         
    
d_jview_addfigure:
    path:    /ajoutFigure/
    defaults: {_controller: DJviewBundle:Default:addfigures}

d_jview_delfigure:
    path:    /supprimerFigure/{id}
    defaults: {_controller: DJviewBundle:Figure:delfigure}
    
d_jview_modification:
    path:    /modificationFigure/{id}
    defaults: {_controller: DJviewBundle:Figure:modificationfigure}
    
d_jview_modification_ajaxupload:
    path:    /ajaxpicture/{id}
    defaults: {_controller: DJviewBundle:Figure:ajaxupload}
    
d_jview_modification_ajaxvideo:
    path:    /test/{id}
    defaults: {_controller: DJviewBundle:Figure:ajaxvideo}
    
d_jview_modification_ajaxdesciption:
    path:    /updatedescription/{id}
    defaults: {_controller: DJviewBundle:Figure:ajaxupdatedescription}