<?php

namespace DJ\viewBundle\Repository;

/**
 * FiguresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FiguresRepository extends \Doctrine\ORM\EntityRepository
{
}
