<?php

namespace DJ\viewBundle\Repository;

/**
 * figureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class figureRepository extends \Doctrine\ORM\EntityRepository
{
}
