<?php

namespace DJ\viewBundle\Repository;

/**
 * FiguresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FiguresRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function myfindall()
    {
        $requry = $this->_em->createQuery('SELECT f FROM DJviewBundle:Figures f JOIN f.picture');

        
        $resultats = $requry->getResult();
        
        return $resultats;
    }
    
    public function pagination($firstResult, $maxResults = 5){
        $requry = $this->_em->createQuery('SELECT f FROM DJviewBundle:Figures f JOIN f.picture')->setFirstResult(($maxResults)*($firstResult-1))->setMaxResults($maxResults);
        
        $page = new \Doctrine\ORM\Tools\Pagination\Paginator($requry);
        
        return $page;
    }
    
    public function getAdvertWithApplications()
    {
      $qb = $this
        ->createQueryBuilder('a')
        ->leftJoin('a.figurename', 'app')
        ->addSelect('app')
      ;

      return $qb
        ->getQuery()
        ->getResult()
      ;
    }


    }
